Algoritmo "atividade003"
// Disciplina   : Algoritmo
// Professor   : Pedro Brandão Neto
// Descrição   : Troca de Valor de Variáveis
// Autor(a)    : Carlos Alexandre Oliveira dos Santos
// Data atual  : 23/09/2024
Var     ]


   a, b: inteiro


Inicio

      escreval("Digite um número")
      leia(a)

      
      
      escreval("Digite um número")
      leia(b)

      a <- a + b
      b <- a - b
      a <- a - b
      
      escreval(a,b)
      
Fimalgoritmo